---
- name: Provision
  hosts: all
  become: true
  become_user: root
  roles:
    - role: common
      tags: common
    - role: crontab
      tags: crontab
    - role: java
      tags: java
    - role: httpd
      tags: httpd
    - role: tomcat
      tags: tomcat
    - role: mysql
      tags: mysql