---
- name: Install packages
  ansible.builtin.dnf:
    name:
      - tomcat9
      - tomcat9-lib
      - tomcat9-webapps
    state: present

- name: Copy server.xml
  ansible.builtin.copy:
    src: files/server.xml
    dest: /etc/tomcat9/server.xml
    owner: root
    group: tomcat
    mode: 0644
    backup: yes

- name: Enable and start tomcat
  ansible.builtin.service:
    name: tomcat9
    state: started
    enabled: true