---
- name: Set timezone to Asia/Tokyo
  community.general.timezone:
    name: Asia/Tokyo

- name: Confirm system locale
  ansible.builtin.command: localectl status
  register: localectl_result
  check_mode: false
  changed_when: false

- name: Set system locale to ja_JP.utf8
  ansible.builtin.command: localectl set-locale LANG=ja_JP.utf8
  when: "'LANG=ja_JP.utf8' not in localectl_result.stdout"

- name: set LANG=ja_JP.UTF-8 in /etc/sysconfig/i18n
  lineinfile:
    dest: /etc/sysconfig/i18n
    regexp: "^LANG="
    line: "LANG=ja_JP.UTF-8"

- name: Install packages
  ansible.builtin.dnf:
    name:
      - python3-pip
      - rsyslog
      - dnf-plugins-core
    state: present

- name: Enable and start rsyslog
  ansible.builtin.service:
    name: rsyslog
    state: started
    enabled: true

- name: Upgrade all packages
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_only: true
